# Generated by Django 5.1.4 on 2024-12-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harbour_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='total_kg',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
