# Generated by Django 5.1.4 on 2024-12-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harbour_app', '0002_alter_fish_total_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='total_kg',
            field=models.CharField(max_length=20),
        ),
    ]
